### ISSUE TITLE
No white space before "editor" for @proceedings entries 

### ISSUE THREAD

**Issue by robstewart57** [aubertc/bib-publication-list#2]
For @proceedings bibtex entries e.g.

```
@proceedings{foo,
   ...
   editor    = {Foo and Bar},
   ...
 }
```

This is presented without a whitespace before the "editor" string e.g.

    Edited by Foo and Barreditor

See examples here:

https://www.macs.hw.ac.uk/~rs46/publications.html

e.g.

    Edited by Robert J. Stewart and Greg J. Michaelsoneditor

1) I assume the lack of a white space character is a bug?

2) What is the last "editor" string for? Even with it, the word "editor" looks unnecessary:

    Edited by Robert J. Stewart and Greg J. Michaelson editor

**Comment by aubertc** [comment]
Thanks for reporting it, and sorry for the time it took me to fix it.

**Comment by robstewart57** [comment]
@aubertc Many thanks for fixing!
